version: "3.7"

services:
  db:
    image: postgres:12.9-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #Tarkista polut kuntoon omalle ympäristöllesi
      #- /haluttupolku/:/db_dumps/
  web:
    restart: unless-stopped
    build: .
    entrypoint: ["./wait_for_pg_and_start.sh", "./run.sh"]
    volumes:
      - .:/code
      #Tarkista polut kuntoon omalle ympäristöllesi
      #- /haluttupolku/uploads/zips:/tmp/zips/
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
