# Generated by Django 2.2 on 2020-02-05 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='default_expense_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='expenseapp.ExpenseType'),
        ),
    ]
