# Generated by Django 2.2.10 on 2020-02-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_auto_20200220_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetype',
            name='requires_start_time',
            field=models.BooleanField(default=False, verbose_name='Requires starting time'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='requires_endtime',
            field=models.BooleanField(default=False, verbose_name='Requires ending date and time'),
        ),
    ]
