# Generated by Django 2.2.10 on 2020-03-02 07:13

from django.db import migrations, models
import expenseapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0003_auto_20200227_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='personno',
            field=models.CharField(help_text='Jos haet kulukorvausta lippukunnalle, syötä tähän lippukunnan Y-tunnus. Y-tunnuksella ei voi hakea kilometrikorvausta tai päivärahoja.', max_length=11, validators=[expenseapp.models.validate_hetu_or_businessid], verbose_name='Person number'),
        ),
    ]
