# Generated by Django 2.2.10 on 2020-03-09 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expenseapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0004_auto_20200302_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdimension',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenseapp.Organisation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='memo',
            field=models.TextField(help_text='eg. "Partiokasvatus" or "Digitaalinen partio-ohjelma"', verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenseapp.Organisation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='personno',
            field=models.CharField(help_text='If you apply for an expense reimbursement for a local group, enter the group’s business ID here. Kilometric allowances and daily subsistence allowances can not be applied for with a business ID.', max_length=11, validators=[expenseapp.models.validate_hetu_or_businessid], verbose_name='Person number'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='accountdimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenseapp.AccountDimension', verbose_name='Cost centre'),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenseapp.Expense'),
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='expensetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenseapp.ExpenseType', verbose_name='Expense type'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenseapp.Organisation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
