# Generated by Django 2.2.10 on 2020-03-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0005_auto_20200309_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='memo',
            field=models.TextField(blank=True, help_text='Eg. Names of the additional passengers, people in the meeting, cost centre or activity sector.', null=True, verbose_name='Info'),
        ),
    ]
