# Generated by Django 2.2.10 on 2020-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0006_auto_20200309_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseline',
            name='receipt',
            field=models.FileField(blank=True, help_text='A scan or picture of the receipt. Accepted formats include PDF, PNG and JPG. Note: The receipt must clearly show what, when and how much has been paid!', null=True, upload_to='uploads/receipts', verbose_name='Receipt'),
        ),
    ]
