# Generated by Django 3.2.12 on 2022-02-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0008_auto_20200324_1133'),
        ('expenseapp', '0008_auto_20200324_1141'),
    ]

    operations = [
    ]
