# Generated by Django 3.2.12 on 2022-02-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0009_infomessage_infomessagetranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infomessage',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='infomessage',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
