# Generated by Django 3.2.12 on 2022-02-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0009_merge_0008_auto_20200324_1133_0008_auto_20200324_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fi', models.CharField(blank=True, max_length=200, verbose_name='Otsikko')),
                ('description_fi', models.TextField(blank=True, max_length=2000, verbose_name='Selite')),
                ('title_se', models.CharField(blank=True, max_length=200, verbose_name='Rubrik')),
                ('description_se', models.TextField(blank=True, max_length=2000, verbose_name='Förklaring')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('description_en', models.TextField(blank=True, max_length=2000, verbose_name='Content')),
                ('start_date', models.DateTimeField(blank=True, verbose_name='Näkyvissä alkaen')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='Päättyy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Edited')),
            ],
            options={
                'verbose_name': 'Tiedoksianto',
                'verbose_name_plural': 'Tiedoksiannot',
            },
        ),
        migrations.AlterModelOptions(
            name='accountdimension',
            options={'verbose_name': 'Kustannuspaikan koodi', 'verbose_name_plural': 'Kustannuspaikat'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Kululasku', 'verbose_name_plural': '  Kululaskut'},
        ),
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Organisaatio', 'verbose_name_plural': ' Organisaatiot'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Henkilötiedot'},
        ),
    ]
