# Generated by Django 3.2.12 on 2022-02-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0010_auto_20220210_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomessage',
            name='end_date',
            field=models.DateTimeField(verbose_name='Visible to'),
        ),
        migrations.AlterField(
            model_name='infomessage',
            name='start_date',
            field=models.DateTimeField(verbose_name='Visible from'),
        ),
    ]
