# Generated by Django 3.2.12 on 2022-02-11 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0012_auto_20220211_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Sent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infomessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Edited'),
        ),
        migrations.AlterField(
            model_name='infomessage',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='Visible to'),
        ),
        migrations.AlterField(
            model_name='infomessage',
            name='start_date',
            field=models.DateTimeField(blank=True, verbose_name='Visible from'),
        ),
    ]
